<?php
/**
* Pacific NM (https://www.pacificnm.com)
*
* @link      https://github.com/pacificnm/pnm for the canonical source repository
* @copyright Copyright (c) 20011-2016 Pacific NM USA Inc. (https://www.pacificnm.com)
* @license
*/
?>
<div class="row">
	<div class="col-xs-12">
		<div class="box box-primary">
			<div class="box-header with-border">
				<h3 class="box-title">
					<i class="<?php echo $this->layout()->pageIcon; ?>" aria-hidden="true"></i>
					<?php echo $this->translate($this->layout()->pageTitle); ?> 
					<small><?php echo $this->translate("View"); ?></small>
				</h3>
				<div class="box-tools">
					<?php echo $this->deleteButton("category-attribute-option-delete", array("id" => $this->entity->getCategoryAttributeOptionId())); ?>
					
					<?php echo $this->updateButton("category-attribute-option-update", array("id" => $this->entity->getCategoryAttributeOptionId())); ?>
				</div>
			</div>
			<div class="box-body box-profile">
                <h3 class="profile-username text-center">
                	<?php echo $this->entity->getCategoryAttributeOptionDisplay(); ?>
                </h3>
                <p class="text-muted text-center">
                	<b><?php echo $this->translate("Value"); ?>: </b>
                	<?php echo $this->entity->getCategoryAttributeOptionValue(); ?>
                </p>
                <ul class="list-group list-group-unbordered">
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Option Id"); ?>:</b>
                    	<?php echo $this->entity->getCategoryAttributeOptionId(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Attribute Id"); ?>:</b>
                    	<?php echo $this->entity->getCategoryAttributeId(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Attribute"); ?>:</b>
                    	<a href="<?php echo $this->url('category-attribute-view', array(
                    	    'id' => $this->entity->getCategoryAttributeId()
                    	)); ?>" title="<?php echo $this->entity->getCategoryAttributeEntity()->getCategoryAttributeName(); ?>">
                    		<?php echo $this->entity->getCategoryAttributeEntity()->getCategoryAttributeName(); ?>
                    	</a>
                    	
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Display"); ?>:</b>
                    	<?php echo $this->entity->getCategoryAttributeOptionDisplay(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Value"); ?>:</b>
                    	<?php echo $this->entity->getCategoryAttributeOptionValue(); ?>
                    </li>
                    <li class="list-group-item">
                    	<b><?php echo $this->translate("Active"); ?>:</b>
                    	<?php echo ($this->entity->getCategoryAttributeOptionActive() == 1 ? $this->translate("Yes") : $this->translate("No")); ?>
                    </li>
                </ul>
            </div>
		</div>
	</div>
</div>